config/routes.rb
Scom::Application.routes.draw do
  resources :cities

  resources :countries

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :profiles
  resources :categories

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  get "profiles/list/:category_id", to: "profiles#list", as: "profiles_list"
  get "profiles/:category_id", to: "profiles#list", as: "profiles_all"
  get "profile/:id", to: "profiles#show", as: "profile_show"
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"

  devise_for :users

  namespace :admin do
    root "base#index"
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    get "categories/dashboard", to: "categories#dashboard", as: "categories_dashboard"
    put "profiles/activate/:id", to: "profiles#activate", as: "profiles_activate"
    
    resources :users
    resources :posts
    resources :categories
    resources :profiles

  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_and_belongs_to_many :categories
	belongs_to :user
  belongs_to :city
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  attr_accessor :country
  attr_accessor :city
  attr_accessor :region
  has_attached_file :logo, 
  :path => ":rails_root/public/profiles/:attachment/:id/logo_:style.:extension",
  :url => "/profiles/:attachment/:id/logo_:style.:extension",
  source_file_options:  { all: '-background transparent' },
  :styles => {
  :thumb    => ['100x100#',  :jpg, :quality => 70],
  :preview  => ['480x480#',  :jpg, :quality => 70],
  :large    => ['600>',      :jpg, :quality => 70],
  :retina   => ['1200>',     :jpg, :quality => 30]
},
:convert_options => {
  :thumb    => '-set colorspace sRGB -strip',
  :preview  => '-set colorspace sRGB -strip',
  :large    => '-set colorspace sRGB -strip',
  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
}
validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png"]
before_save :sanitize_url
  # Scopes
  scope :active, lambda {
    where(status: 'a')
    .order("updated_at DESC")
  }
  scope :registred, lambda {
    where(status: 'r')
    .order("updated_at DESC")
  }
  scope :deleted, lambda {
    where(status: 'd')
    .order("updated_at DESC")
  }
  def self.in_categories(category_ids=[])
    return all if category_ids.blank? || category_ids.empty?
    includes(:categories).where(categories: { id: category_ids })
  end
  
  def sanitize_url
      unless self.url.include?("http://") || self.url.include?("https://")
        self.url = "http://" + self.url
      end
   end
   
  def should_generate_new_friendly_id?
    new_record?
  end
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /admin/profiles
  # GET /admin/profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /admin/profiles/1
  # GET /admin/profiles/1.json
  def show
  end

  # GET /admin/profiles/new
  def new
    @profile = Profile.new
  end

  # GET /admin/profiles/1/edit
  def edit
  end

  # POST /admin/profiles
  # POST /admin/profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to [:admin, @profile], notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/profiles/1
  # PATCH/PUT /admin/profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to [:admin, @profile], notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/profiles/1
  # DELETE /admin/profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to admin_profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #PUT /admin/profiles/1
  #PUT /admin/profiles/1.json
  def activate
    @profile = Profile.find(params[:id])
    @profile.update(status: 'a')
    
    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.js   { render :nothing => true }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :url, :phone, :place_id, :orgtype, :full_description, :short_description, :workers, :found_year, :status, :user_id, :lat, :lng, :address, :category_ids => [])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update, :destroy]
  

  # GET /profiles
  # GET /profiles.json
  def index
    
    @profiles = Profile.in_categories(params[:profile][:category_ids]).active.page(params[:page]).per(10)
  end

  #GET /profiles/list/1
  def list
    <<-DOC
    if params[:category_id]
      @category_id = params[:category_id]
      @categories = Category.find(@category_id)
    else
      @categories = Category.roots
    end
    @profiles = @categories.profiles.active
    DOC

    
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.friendly.find(params[:id])
    if request.path != profile_path(@profile)
    redirect_to @profile, status: :moved_permanently
    end

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    params[:profile][:category_ids] ||= []
    @town = set_city
    params[:profile][:city_id] = @town.id
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_profile
      @profile = Profile.where(user_id: current_user).first
      #@profile = Profile.find(params[:id])
    end

    def set_city

      c = Country.where(name: params[:profile][:country]).first_or_create
      r = Region.where(name: params[:profile][:region], country: c).first_or_create
      t = City.where(name: params[:profile][:city], country: c, region: r).first_or_create
      return t
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.permit(:category_ids => [])
      params.require(:profile).permit(:name, :logo, :country, :city, :requisites, :city_id, :region, :url, :phone, :place_id, :orgtype, :full_description, :short_description, :workers, :found_year, :lat, :lng, :address, :category_ids => [])
    end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
<%= form_for([:admin, @profile], html: { class: 'form-horizontal profile' }) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :email, :include_blank => true %>
  </div>
  <div>
    <% for category in Category.all %>
    <div>
      <%= check_box_tag "profile[category_ids][]", category.id, @profile.categories.include?(category) %>
      <%= category.name %>
    </div>
    <% end %>
  </div>
<div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.number_field :place_id %>
  </div>
  <div class="field">
    <%= f.label :orgtype %><br>
    <%= f.number_field :orgtype %>
  </div>
  <div class="field">
    <%= f.label :full_description %><br>
    <%= f.text_area :full_description %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :workers %><br>
    <%= f.number_field :workers %>
  </div>
  <div class="field">
    <%= f.label :found_date %><br>
    <%= f.date_select :found_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/profiles/edit.html.erb
<div class="page-header">
  <h1>Editing profile</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @profile], class: 'btn btn-default' %>
<%= link_to 'Back', admin_profiles_path, class: 'btn btn-default' %>

app/views/admin/profiles/index.html.erb
<div class="page-header">
  <h1>Listing profiles</h1>
</div>
<p><%= link_to "Back to Admin", admin_root_path %></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
      <td><%= profile.status %>
      <%= link_to 'Activate', admin_profiles_activate_path(profile), :method => :put, class: 'link-activate', :remote=>true %></td>
      <td><%= profile.name %></td>
        <td><%= link_to 'Show', [:admin, profile], class: 'btn btn-default btn-xs' %>
        <td><%= link_to 'Edit', edit_admin_profile_path(profile), class: 'btn btn-default btn-xs' %>
        <%= link_to 'Destroy', [:admin, profile], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_admin_profile_path, class: 'btn btn-primary' %>
<script type="text/javascript">
$(document).on('ajax:success', '.link-activate', function() {
    // .parent() is the div containing this "X" delete link
    $(this).parent().parent().slideUp();
    }
);
</script>

app/views/admin/profiles/new.html.erb
<div class="page-header">
  <h1>New profile</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_profiles_path, class: 'btn btn-default' %>

app/views/admin/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_profile_path(@profile), class: 'btn btn-default' %>
<%= link_to 'Back', admin_profiles_path, class: 'btn btn-default' %>