config/routes.rb
Scom::Application.routes.draw do
  resources :cities

  resources :countries

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :profiles
  resources :categories

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  get "profiles/list/:category_id", to: "profiles#list", as: "profiles_list"
  get "profiles/:category_id", to: "profiles#list", as: "profiles_all"
  get "profile/:id", to: "profiles#show", as: "profile_show"
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"

  devise_for :users

  namespace :admin do
    root "base#index"
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    get "categories/dashboard", to: "categories#dashboard", as: "categories_dashboard"
    put "profiles/activate/:id", to: "profiles#activate", as: "profiles_activate"
    
    resources :users
    resources :posts
    resources :categories
    resources :profiles

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_tree
  has_and_belongs_to_many :profiles
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]



  def dashboard
    @categories = Category.roots
  end

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    if params[:category][:parent_id].to_i>0
      parent = Category.find_by_id(params[:category].delete(:parent_id))
      @category = parent.children.build(category_params)
    else
      @category = Category.new(category_params)
    end

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_dashboard_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :ok, location: admin_categories_dashboard_path }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_dashboard_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_categories_dashboard_path }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_dashboard_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category].permit(:name, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/views/admin/categories/_category.html.erb
<li>
  <%= Category.name %>

  <% unless Category.child_ids.empty? %>
    <ul>
      <%= render Category.children %>
    </ul>
  <% end %>
</li>

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :parent_id %><br />
    <%= f.select :parent_id, Category.all.collect {|a| [a.name, a.id]}, :include_blank => true %>
  </p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/dashboard.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<hr/>

<ul class="fa-ul">
    <% @categories.each do |category| %>
 <li class="margin-md-down">
    <i class="fa fa-arrow-circle-o-right small"></i>&nbsp;&nbsp;
    
        <%= link_to category.name, edit_admin_category_path(category) %>
        <%= link_to 'Destroy', [:admin, category], method: :delete, data: { confirm: 'Are you sure?' } %>
        <% if category.children %>
   		 <ul class="fa-ul">
   		 <li class="margin-md-down">
	    	<% category.children.each do |subcategory| %>
	    	<i class="fa fa-arrow-circle-o-right small"></i>&nbsp;&nbsp;
	    	<%= link_to subcategory.name, edit_admin_category_path(subcategory) %>
	    	<%= link_to subcategory.name, edit_admin_category_path(subcategory) %>
	        <%= link_to 'Destroy', [:admin, subcategory], method: :delete, data: { confirm: 'Are you sure?' } %>
	    	<% end %>
	    </ul>
    	<% end %>

  </li>
        
    <% end %>
</ul>

<hr/>
<br>

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', admin_categories_dashboard_path %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<hr/>


<div class="row">
    <% @categories.each do |category| %>
 	<div class="col-xs-3">   
        <%= link_to category.name, category %>
      <br class="margin-md-down">
        <% if category.children %>
   		 
	    	<% category.children.each do |subcategory| %>
	    	<sup><%= link_to subcategory.name, category_path(subcategory) %></sup>
	    	
	    	<% end %>

    	<% end %>

         </div>
    <% end %>
 
</div>

<hr/>
<br>

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>